name: Publish to NuGet
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: restore dependencies
        run: nuget restore $SOLUTION
      
      - name: Build
        run: dotnet build MseeqU.sln --configuration Release --no-restore
      
      - name: Prepare NuGet package
        run: nuget pack TelegramBot\MseeqU.nuspec -IncludeReferencedProjects
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: '5.x'
          
      - name: Publish
        if: startswith(github.ref, 'refs/heads/release')
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json'
